apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vy1j
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0025-tenant/tkrw-pr712-0075-0025-app/devfile-sample-vy1j@sha256:327cf1425bdaf9c370881826c81678159f21e656252b9406ad7c14a0e1a8e378
        name: my-nodejs
        resources: {}
status: {}
